#!/usr/bin/env node
/**
 * Build the bundled native front-end for Capacitor (iOS/Android).
 *
 * Next.js can't `output: export` a project that also contains server route
 * handlers (`/api/*`) or dynamic SSR pages (`/e/[id]`) — and it shouldn't: those
 * are the backend and stay on Vercel. So for the native bundle we temporarily
 * move the server-only routes aside, statically export just the app UI into
 * `out/`, then restore everything. The exported app calls the hosted API via
 * NEXT_PUBLIC_API_BASE (see src/lib/apiBase.ts) with CORS allow-listed in
 * middleware.ts. The result is a genuine offline-capable bundled app, not a
 * URL wrapper.
 *
 * Usage:
 *   NEXT_PUBLIC_API_BASE=https://your-prod-domain npm run build:native
 *   npx cap sync           # copy out/ into the native projects
 */
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const APP = join(ROOT, 'src', 'app');
const STASH = join(ROOT, '.native-stash');

// Server-only routes that must not be part of a static export.
const SERVER_ONLY = ['api', 'e'];

// The strict CSP mints a nonce per response, which means the document shell has
// to render per request — so layout.tsx declares `force-dynamic`. A static
// export has no server and no middleware, so there is no nonce to mint and no
// way to honour that: Next refuses to export /_not-found and the build dies
// with "Page with `dynamic = force-dynamic` couldn't be exported".
//
// Next requires this field to be a literal string ("Next.js can't recognize the
// exported `dynamic` field in route. It needs to be a static string"), so it
// cannot be a ternary on NATIVE_EXPORT. We swap the line for the export and put
// the file back afterwards, exactly like the server-only routes above.
const LAYOUT       = join(APP, 'layout.tsx');
const LAYOUT_BAK   = join(STASH, 'layout.tsx.bak');
const DYNAMIC_SSR    = "export const dynamic = 'force-dynamic';";
const DYNAMIC_STATIC = "export const dynamic = 'force-static';";

const apiBase = process.env.NEXT_PUBLIC_API_BASE || '';
if (!apiBase) {
  console.warn(
    '\n⚠  NEXT_PUBLIC_API_BASE is not set — the bundled app will try same-origin\n' +
    '   API calls and fail on device. Set it to your hosted origin, e.g.\n' +
    '   NEXT_PUBLIC_API_BASE=https://nova-phi-liart.vercel.app npm run build:native\n'
  );
}

function stash() {
  mkdirSync(STASH, { recursive: true });
  for (const dir of SERVER_ONLY) {
    const from = join(APP, dir);
    if (existsSync(from)) renameSync(from, join(STASH, dir));
  }

  const layout = readFileSync(LAYOUT, 'utf8');
  // Fail loudly rather than silently exporting a broken bundle: if the line
  // moved or was reworded, this script's assumption is stale and the person
  // changing it needs to know.
  if (!layout.includes(DYNAMIC_SSR)) {
    throw new Error(
      `build-native: expected ${JSON.stringify(DYNAMIC_SSR)} in src/app/layout.tsx.\n` +
      '  The static export cannot run with force-dynamic; update DYNAMIC_SSR in this script.'
    );
  }
  writeFileSync(LAYOUT_BAK, layout);
  writeFileSync(LAYOUT, layout.replace(DYNAMIC_SSR, DYNAMIC_STATIC));
}
function restore() {
  for (const dir of SERVER_ONLY) {
    const from = join(STASH, dir);
    if (existsSync(from)) renameSync(from, join(APP, dir));
  }
  if (existsSync(LAYOUT_BAK)) writeFileSync(LAYOUT, readFileSync(LAYOUT_BAK, 'utf8'));
  rmSync(STASH, { recursive: true, force: true });
}

console.log('▶ Building bundled native front-end (static export)…');
rmSync(join(ROOT, 'out'), { recursive: true, force: true });
// `next dev` writes a route validator into .next/dev/types that imports every
// route by path, and tsconfig type-checks it. Those imports dangle the moment we
// stash /api and /e, so a leftover dev directory fails the build with "Cannot
// find module '../../../src/app/e/[id]/page.js'" — on this machine only, which
// is why CI never saw it. It is regenerated by the next `next dev`.
rmSync(join(ROOT, '.next', 'dev'), { recursive: true, force: true });
stash();
try {
  execSync('next build', {
    stdio: 'inherit',
    env: { ...process.env, NATIVE_EXPORT: '1' },
  });
  console.log('\n✓ Static bundle written to out/.');
  console.log('  Next: npx cap sync  →  npx cap open ios | android');
} finally {
  restore();
  console.log('✓ Restored server routes (/api, /e).');
}
